# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sam Barnett | Perth UX Developer
description: "A Front-end Developer and User Experience Designer based in Perth, WA. I love to bring designs through from pen-and-pad sketches to fully functioning web experiences that people love to use."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://samuelbar.net" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown

# theme: jekyll-theme-boilerplate

# Sass settings
sass:
  add_charset: true
  sass_dir: _sass
  style: compressed

include: ['_pages']

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  # - assets/sass

# Plugin settings
plugins:
  - jekyll-sitemap
  - jekyll-autoprefixer
